# Generated by Django 5.1.1 on 2024-09-21 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturers',
            fields=[
                ('manufacturerID', models.AutoField(primary_key=True, serialize=False)),
                ('manufacturerName', models.CharField(max_length=50)),
                ('manufacturerCountry', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Appliances',
            fields=[
                ('applianceID', models.AutoField(primary_key=True, serialize=False)),
                ('applianceName', models.CharField(max_length=50)),
                ('applianceneedsElectric', models.BooleanField()),
                ('applianceNeedsGas', models.BooleanField()),
                ('applianceRoom', models.CharField(max_length=50)),
                ('applianceManufactuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod5app.manufacturers')),
            ],
        ),
    ]
