# Generated by Django 5.1.1 on 2024-09-21 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mod5app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appliances',
            new_name='Appliance',
        ),
        migrations.RenameModel(
            old_name='Manufacturers',
            new_name='Manufacturer',
        ),
    ]
