# Generated by Django 5.1.1 on 2024-09-21 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mod5app', '0003_rename_applianceneedselectric_appliance_applianceneedselectric'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appliance',
            old_name='applianceManufactuer',
            new_name='applianceManufacturer',
        ),
    ]
