# Generated by Django 5.1.1 on 2024-09-21 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod5app', '0004_rename_appliancemanufactuer_appliance_appliancemanufacturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliance',
            name='applianceNeedsWater',
            field=models.BooleanField(default=True),
        ),
    ]
