# Generated by Django 5.1.1 on 2024-09-21 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod5app', '0005_appliance_applianceneedswater'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliance',
            name='applianceNeedsWater',
            field=models.BooleanField(),
        ),
    ]
